import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo Application",
  description: "Generated by Tayut Singchai",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
